### ISSUE TITLE
No SELECT privileges result in silent failure

### ISSUE THREAD

**Issue by vartec** [noplay/python-mysql-replication#116]
Steps to reproduce:
1. `GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'a_user'@'%'`
2. `REVOKE SELECT ON`your_db`.* TO 'a_user'@'%'` (or just don't grant it).
3. use pymysqlreplication 

Expected result: 
Raising an Exception stating that user has no privilege to read table's column information

Actual result:
Receiving RowEvents with no statement rows associated with it.

Background:
`BinLogStreamReader. __get_table_information` tries to access column information. Having no privileges this does not return error, but rather no rows. This information is later used in `RowEvent.__init__`. 
https://github.com/vartec/python-mysql-replication/blob/a4aa08c746cf69ed141301db81b6660655eff3c4/pymysqlreplication/row_event.py#L55-L58

 Having no column information causes it to silently marked as `completed = False`, and subsequently not fetching any rows.

**Comment by bjoernhaeuser** [comment]
See also here: https://github.com/noplay/python-mysql-replication/pull/184

It's a design decision in the end, which resulted in user depending on the current behaviour. Nonetheless: patches welcome :)
