### ISSUE TITLE
Values missing if database rights aren't granted

### ISSUE THREAD

**Issue by foxycode** [noplay/python-mysql-replication#131]
Took me lot of time to uncover that user without database rights (on with  REPLICATION SLAVE and REPLICATION CLIENT) can't see table structure from information_schema and it's why event values aren't dumped.

It is possible read data from strem even without that rights?

**Comment by bjoernhaeuser** [comment]
Nope, where would you get that information from?

**Comment by foxycode** [comment]
@bjoernhaeuser Here data about table structure are read: https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/binlogstream.py#L332

If I haven't rights to that database/table, query returns empty result and row events doesn't return column data. I think that column data should be present in stream, even if I don't have database right. After all, how mysql slave could replicate them if they weren't. But I didn't examined your source too much to know how to handle it.

**Comment by bjoernhaeuser** [comment]
@foxycode they are not included in the stream :( the stream misses the column name and data type, it only carries the position of these columns.

**Comment by foxycode** [comment]
@bjoernhaeuser I understand that column names and data types aren't in stream. But it is possible to parse at least raw data and return them as tupple for example? Is it possible to decode them properly without knowing data type?

And if not, could you please mention information about needed rights in README somewhere so someone else don't need to deal with this?

Thanks

**Comment by noplay** [comment]
Yeah you can imagine an option turning off the mapping to column name (the information schema is only need for that).

**Comment by muayyad-alsadi** [comment]
please update documentation to indicate we should have

```
CREATE USER 'repl'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
GRANT REPLICATION CLIENT ON *.* TO 'repl'@'%';
GRANT SELECT ON *.* TO 'repl'@'%';
```

**Comment by bjoernhaeuser** [comment]
Done! https://github.com/noplay/python-mysql-replication/pull/184
