### ISSUE TITLE
Cannot get all the bin-log info

### ISSUE THREAD

**Issue by hzruandd** [noplay/python-mysql-replication#133]
when i run the redis_cache.py, i found an issue:
i had executed some sql(more than 30), but it can be only got the ahead of 11 sql from bin-log. 
```
mysql> SHOW MASTER STATUS;
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000001 |     4437 |              |                  |                   |
+------------------+----------+--------------+------------------+-------------------+
1 row in set (5.47 sec)
```
and then,i executed another sql,but it(redis_cache.py) ignore the others(such update and delete).

```
SHOW MASTER STATUS;
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000001 |     9430 |              |                  |                   |
+------------------+----------+--------------+------------------+-------------------+
```
as we can see,the mysql server's bin-log had increased.

**Comment by bjoernhaeuser** [comment]
@hzruandd we need more information :) 

What SQL do you insert? How does the schema looks? The `redis_cache` only updates events which have an "id" column

**Comment by hzruandd** [comment]
oh，sorry, i had made a mistake, and now  i had resolved this issue. but i found another issue that it cannot decode the utf8mb4.

**Comment by bjoernhaeuser** [comment]
okay, so this is closed :)

there was an issie with utf8mb4, but I cant remember the solution.
