### ISSUE TITLE
The new BinLogStreamReader will kill the old one? 

### ISSUE THREAD

**Issue by JackWang917** [noplay/python-mysql-replication#137]
When I kicked off my second BinlogStreamReader, the first one(running) was suddenly stopped. Was the new BinlogStreamReader killed the current running one? The two StreamReader were monitoring the same bin-log file.
My code as following:
self.stream = BinLogStreamReader(connection_settings = mysql_settings,
                            only_events = [DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent], 
                            blocking = True, resume_stream = True, server_id=2, log_file=bin-log.1098, log_pos=88569)
Thanks in advance!

**Comment by noplay** [comment]
If you use the same server id, MySQL will kill the first connection
