### ISSUE TITLE
why `self.packet.read_bytes + 1 < self.event_size` here?

### ISSUE THREAD

**Issue by siddontang** [noplay/python-mysql-replication#140]
Hi @noplay 

In my go mysql replication, we meet a panic when decoding row events, here https://github.com/siddontang/go-mysql/issues/33 (please ignore the Chinese words :-) 

I find that you use `self.packet.read_bytes + 1 < self.event_size` https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/row_event.py#L391, can you tell me why using +1 here? I think `self.packet.read_bytes < self.event_size` is ok too. 

Thank you.

**Comment by noplay** [comment]
I can't remember. If you remove the + 1 it's work?
