### ISSUE TITLE
question about only_tables in BinLogStreamReader 

### ISSUE THREAD

**Issue by JackWang917** [noplay/python-mysql-replication#141]
I'd like to know the parameter "only_tables" would tell MysqlServer :"just give me the specific tables" or It still get every thing from mysql bin-log but just filter it in client side.

My problem is that my replicate process very slow, it can not catchup the bin-log. But when I indicate the only_tables in BinLogStreamReader, it still slow, almost no any effect. My database has 50 tables, but I only need 6 tables.

How can I expedite the process please, or how can I let Mysql bin log just gives me the 6 tables log data not everything.

**Comment by noplay** [comment]
It get the full log.They are no way to get only what you want. But when you use only_table we skip the parsing of the fields i t should be a little faster.
