### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by baloo** [noplay/python-mysql-replication#157]
Do you have any blocker for a new release? I got a bunch of fixes in current master branch yet to be released. That would easy things for me.

If there any blocker, I can probably help to get them fixed.

**Comment by noplay** [comment]
And it's released :) I also add you to the github.

I could add you on PyPi to allow you to release new build. Until the end of the year I don't plan additional dev on the project

**Comment by baloo** [comment]
wow:) thanks!
