### ISSUE TITLE
discrepancy between python datetime.time and mysql TIME

### ISSUE THREAD

**Issue by abrarsheikh** [noplay/python-mysql-replication#167]
MYSQL [time](http://dev.mysql.com/doc/refman/5.7/en/time.html) supports a range of '-838:59:59.000000' to '838:59:59.000000' where was python [datetime.time](https://docs.python.org/2/library/datetime.html#time-objects) has a range of 0 <= hour < 24, 0 <= minute < 60, 0 <= second < 60, 0 <= microsecond < 1000000. It would be incorrect to encode mysql time into python datetime.time.

**Comment by baloo** [comment]
"The hours part may be so large because the TIME type can be used not only to represent a time of day (which must be less than 24 hours), but also elapsed time or a time interval between two events (which may be much greater than 24 hours, or even negative)."

What about datetime.timedelta ?

**Comment by abrarsheikh** [comment]
@baloo i think datetime.timedelta can support the range of mysql time. Currently `python-mysql-replication` encode mysql time into pyhton time, can i create a pull request which encodes mysql time to python datetime.timedelta ?

**Comment by abrarsheikh** [comment]
encoding `838:59:59.999999` as `datetime.timedelta`
```
>>> d = timedelta(microseconds=999999, hours=838, minutes=59, seconds=59)
>>> d
datetime.timedelta(34, 82799, 999999)
```
Validation:
```
(((838*60) + 59)*60 + 59)*1000000 + 999999 = 3,020,399,999,999 microsecond
(34*24*60*60 + 82799)*1000000 + 999999 = 3,020,399,999,999 microsecond
```
encoding `-838:59:59.999999` as `datetime.timedelta`
```
>>> d = timedelta(microseconds=999999, hours=-838, minutes=59, seconds=59)
>>> d
datetime.timedelta(-35, 10799, 999999)
```
Validation:
```
(((-838*60) + 59)*60 + 59)*1000000 + 999999 = -3,013,200,000,001
(-35*24*60*60 + 10799)*1000000 + 999999 = -3,013,200,000,001
```
