### ISSUE TITLE
not work with msyql 5.6.31@ubuntu15.10 in  vagrantbox 

### ISSUE THREAD

**Issue by coco101000000000** [noplay/python-mysql-replication#168]
it work well on  mysql5.7.13 @ubuntu16.04 in vm

**Comment by noplay** [comment]
Hi,

Do you have more informations about the issue? Error messages?

**Comment by coco101000000000** [comment]
Mysql @ vagrant-ubuntu:


Server version: 5.6.31-0ubuntu0.15.10.1-log (Ubuntu)


mysql> show master status;
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000015 |     2357 |              |                  |                   |
+------------------+----------+--------------+------------------+-------------------+

Replication @ vagrant-ubuntu:
Only have  QueryEvent ,XidEvent and RotateEvent output 

python2 redis_replication2.py 
pymysqlreplication.event.RotateEvent object at 0x7fb9f0b49690
pymysqlreplication.event.FormatDescriptionEvent object at 0x7fb9f0b49710
pymysqlreplication.event.QueryEvent object at 0x7fb9f0b497d0
pymysqlreplication.event.QueryEvent object at 0x7fb9f0b49890
pymysqlreplication.event.XidEvent object at 0x7fb9f0b49950
pymysqlreplication.event.QueryEvent object at 0x7fb9f0b49a10
pymysqlreplication.event.QueryEvent object at 0x7fb9f0b49ad0
pymysqlreplication.event.XidEvent object at 0x7fb9f0b49b90
pymysqlreplication.event.QueryEvent object at 0x7fb9f0b49c50
pymysqlreplication.event.QueryEvent object at 0x7fb9f0b49d10

Python @ vagrant-ubuntu:

Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2

**Comment by coco101000000000** [comment]
Mysql @ VM-ubuntu:


Server version: 5.7.13-0ubuntu0.16.04.2-log (Ubuntu)

mysql> show master status;
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000026 |      154 |              |                  |                   |
+------------------+----------+--------------+------------------+-------------------+


Replication @  VM-ubuntu:

python redis_replication2.py 

pymysqlreplication.event.RotateEvent object at 0x7f53332fe3d0
pymysqlreplication.event.FormatDescriptionEvent object at 0x7f53332fe450
pymysqlreplication.event.QueryEvent object at 0x7f53332fe590
pymysqlreplication.row_event.TableMapEvent object at 0x7f53332fe610
pymysqlreplication.row_event.DeleteRowsEvent object at 0x7f53332fe910
pymysqlreplication.event.XidEvent object at 0x7f53332fe9d0
pymysqlreplication.event.QueryEvent object at 0x7f53332feb10
pymysqlreplication.row_event.TableMapEvent object at 0x7f53332feb90
pymysqlreplication.row_event.DeleteRowsEvent object at 0x7f53332fed10
pymysqlreplication.event.XidEvent object at 0x7f53332fedd0
pymysqlreplication.event.QueryEvent object at 0x7f53332fef10
pymysqlreplication.row_event.TableMapEvent object at 0x7f53332fef90
pymysqlreplication.row_event.DeleteRowsEvent object at 0x7f533308d150
pymysqlreplication.event.XidEvent object at 0x7f533308d210
pymysqlreplication.event.QueryEvent object at 0x7f533308d350
pymysqlreplication.row_event.TableMapEvent object at 0x7f533308d3d0
pymysqlreplication.row_event.DeleteRowsEvent object at 0x7f533308d550
pymysqlreplication.event.XidEvent object at 0x7f533308d610
pymysqlreplication.event.QueryEvent object at 0x7f533308d750
pymysqlreplication.row_event.TableMapEvent object at 0x7f533308d7d0
pymysqlreplication.row_event.DeleteRowsEvent object at 0x7f533308d950
pymysqlreplication.event.XidEvent object at 0x7f533308da10
pymysqlreplication.event.QueryEvent object at 0x7f533308db50
pymysqlreplication.row_event.TableMapEvent object at 0x7f533308dbd0
pymysqlreplication.row_event.WriteRowsEvent object at 0x7f533308dd50
pymysqlreplication.event.XidEvent object at 0x7f533308de10
pymysqlreplication.event.QueryEvent object at 0x7f533308df50
pymysqlreplication.row_event.TableMapEvent object at 0x7f533308dfd0
pymysqlreplication.row_event.UpdateRowsEvent object at 0x7f5333091190
pymysqlreplication.event.XidEvent object at 0x7f5333091250

Python @  VM-ubuntu:

Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2

**Comment by coco101000000000** [comment]
from pymysqlreplication import BinLogStreamReader

MYSQL_SETTINGS = {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "passwd": "root"
}


def main():
    stream = BinLogStreamReader(connection_settings=MYSQL_SETTINGS, server_id=3, blocking=True)

    for binlogevent in stream:
        print(binlogevent)


if __name__ == "__main__":
    main()

**Comment by coco101000000000** [comment]
from pymysqlreplication import BinLogStreamReader

MYSQL_SETTINGS = {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "passwd": "root"
}


def main():
    stream = BinLogStreamReader(connection_settings=MYSQL_SETTINGS, server_id=3, blocking=True)

    for binlogevent in stream:
        print(binlogevent)


if __name__ == "__main__":
    main()

**Comment by coco101000000000** [comment]
There has no error message, all seems run well, there only different is the output event.

**Comment by bjoernhaeuser** [comment]
And what is not working? Seeing no error and not a good explanation of your problem

**Comment by coco101000000000** [comment]
for binlogevent in stream:
        binlogevent.dump()

It appears again.

no updateEvent,no deleteEvent.
update,delete,create all in QueryEvent.
==================================
C:\Python27\python.exe G:/work/peewee/redis_replication2.py
=== QueryEvent ===
Date: 2016-10-20T12:03:44
Log position: 3231
Event size: 19
Read bytes: 19
Schema: 
Execution time: 0
Query: BEGIN
()
=== QueryEvent ===
Date: 2016-10-20T12:03:44
Log position: 3375
Event size: 125
Read bytes: 125
Schema: test
Execution time: 0
Query: UPDATE `contract_apply` SET `apply_name`='鍚勪釜鍏竷鎶ュ憡yy' WHERE (`id`='17')
()
=== XidEvent ===
Date: 2016-10-20T12:03:44
Log position: 3402
Event size: 8
Read bytes: 8
Transaction ID: 63
()
=== QueryEvent ===
Date: 2016-10-20T12:03:45
Log position: 3440
Event size: 19
Read bytes: 19
Schema: 
Execution time: 0
Query: BEGIN
()
=== QueryEvent ===
Date: 2016-10-20T12:03:45
Log position: 3569
Event size: 110
Read bytes: 110
Schema: test
Execution time: 0
Query: UPDATE `contract_apply` SET `apply_name`='erwyy' WHERE (`id`='11')
()
=== XidEvent ===
Date: 2016-10-20T12:03:45
Log position: 3596
Event size: 8
Read bytes: 8
Transaction ID: 65
()
=== QueryEvent ===
Date: 2016-10-20T13:16:06
Log position: 3634
Event size: 19
Read bytes: 19
Schema: 
Execution time: 0
Query: BEGIN
()
=== QueryEvent ===
Date: 2016-10-20T13:16:06
Log position: 3743
Event size: 90
Read bytes: 90
Schema: test
Execution time: 0
Query: DELETE FROM `contract_apply` WHERE (`id`='40')
()
=== XidEvent ===
Date: 2016-10-20T13:16:06
Log position: 3770
Event size: 8
Read bytes: 8
Transaction ID: 73
()
=== QueryEvent ===
Date: 2016-10-20T13:17:06
Log position: 3940
Event size: 85
Read bytes: 85
Schema: test
Execution time: 0
Query: INSERT INTO `contract_apply` () VALUES ()
()
=== XidEvent ===
Date: 2016-10-20T13:17:06
Log position: 3967
Event size: 8
Read bytes: 8
Transaction ID: 74
()

**Comment by coco101000000000** [comment]
log-bin=mysql-bin
binlog_format=mixed
skip-name-resolve
skip-grant-tables

**Comment by coco101000000000** [comment]
Here is  the mysql-bin log files.

[data.zip](https://github.com/noplay/python-mysql-replication/files/540842/data.zip)

**Comment by coco101000000000** [comment]
I konw why this setting "binlog-format    = row" , I set to mixed.
