### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by noplay** [noplay/python-mysql-replication#171]
Hi everyone,

Do you want me to push a new version on PyPi?

**Comment by kdparker** [comment]
Would definitely be for a new version being released on PyPi

**Comment by noplay** [comment]
I will take care of this during the week

Le lun. 28 nov. 2016 à 22:29, Keegan Parker <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
Released! 

Thanks a lot
