### ISSUE TITLE
mySQL 5.7 support roadmap

### ISSUE THREAD

**Issue by schmohlio** [noplay/python-mysql-replication#178]
Hi all,

Thanks again for the great project. Since I've seen some rumblings of 5.7 support, I was wondering if any documentation could be exposed w.r.t. a roadmap / which feature branches are supported / known limitations. Thanks inadvance!

**Comment by kdparker** [comment]
I think this might be a case of the README being outdated? We're running all of the tests in 5.7 on travis successfully.

**Comment by schmohlio** [comment]
awesome, thanks for the quick response!

**Comment by noplay** [comment]
You can open a PR for the README ;)

Le jeu. 8 déc. 2016 à 20:26, Matthew Schmohl <notifications@github.com> a
écrit :
