### ISSUE TITLE
caution: misleading output if user do not have SELECT privilege on information_schema

### ISSUE THREAD

**Issue by danfengcao** [noplay/python-mysql-replication#183]
@imzcy1987 and I took a lot of time to uncover values missing if user do not have SELECT privilege on information_schema. Same issues have reported in #116 , #131 and #172 .

The root cause i found is that information_schema is a special db, Each MySQL user has the right to access these tables, but can see only the rows in the tables that correspond to objects for which the user has the proper access privileges([http://dev.mysql.com/doc/refman/5.7/en/information-schema.html](http://dev.mysql.com/doc/refman/5.7/en/information-schema.html) ). So in function [binlogstream.__get_table_information()](https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/binlogstream.py#L480), it always return empty either the table actually not existing or the user have no privilege on information_schema.COLUMNs.

I strongly suggest @noplay to update documentation  to indicate we should have
`GRANT SELECT, REPLICATION SLAVE, SUPER ON *.* TO user`

I also suggest to add an assertion before [https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/binlogstream.py#L471](https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/binlogstream.py#L471) , to raise Exception stating that user has  no SELECT privilege on information_schema.

I think it's important to pay attention to fix this bug or update documentation. Then #116 , #131 and #172 can be closed

**Comment by noplay** [comment]
HI,

Pull requests are welcome. You can edit the documentation here:
https://github.com/noplay/python-mysql-replication/tree/master/docs

I think the permission check need to be done just one time at connection to the DB.
