### ISSUE TITLE
only_tables issue

### ISSUE THREAD

**Issue by daro997** [noplay/python-mysql-replication#193]
Hello,

Does the only_tables option should work?
I have two tables with name: table-one, table-two
I try 
TABLES = ['database.table-one','database.table-two']
only_option = TABLES

but it doesn't work.
dash in table name is necessary

Regards

**Comment by baloo** [comment]
Hi,

You are expected to not include the schema name in the `only_tables` option. If you want `only_schema` is also available.

Something like:
``` python
self.stream = BinLogStreamReader(
  self.database,
  server_id=1024,
  only_schemas=['database'],
  only_tables = ['table-one'])
```

**Comment by daro997** [comment]
Hello, 

I want to follow two tables:
table-one and table-two.

option that i want to use is of course only_tables, but when I used
TABLES = ['database.table-one','database.table-two']

stream = BinLogStreamReader(
  server_id=1024,
  only_schemas=['database'],
  only_tables = TABLES)

it doesn't work

**Comment by baloo** [comment]
Use:
``` python
TABLES = ['table-one','table-two']

stream = BinLogStreamReader(
server_id=1024,
only_schemas=['database'],
only_tables = TABLES)
```

**Comment by daro997** [comment]
It still doesn't work. 
Is it possible to debug this function?

**Comment by Onway** [comment]
`only_schemas` and `only_tables ` just work on rows events, which are  `UpdateRowsEvent`, `WriteRowsEvent`, `DeleteRowsEvent` and `TableMapEvent`.
