### ISSUE TITLE
BinLogStreamReader object log_pos  parameter invalidation

### ISSUE THREAD

**Issue by basebase** [noplay/python-mysql-replication#207]
I using pymysqlreplication read mysql binglog
setting log_file and log_pos value

+------------------+------------+----------------+--------------------+---------------------+
| File             |   Position | Binlog_Do_DB   | Binlog_Ignore_DB   | Executed_Gtid_Set   |
|------------------+------------+----------------+--------------------+---------------------|
| mysql-bin.000027 |       2566 |                |                    |                     |
+------------------+------------+----------------+--------------------+---------------------+

log_pos = 2566

Still read the data before 2566

code:

>  
      def main():

        stream = BinLogStreamReader(
        connection_settings=mysql_config.MYSQL_SETTINGS,
        server_id=100,
        log_file='mysql-bin.000027',
        log_pos=2566,
        blocking=True,
        only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent])

    for binlogevent in stream:
        for row in binlogevent.rows:
            event = {"schema": binlogevent.schema, "table": binlogevent.table}

            if isinstance(binlogevent, DeleteRowsEvent):
                event["action"] = "delete"
                event.update(row["values"].items())
            elif isinstance(binlogevent, UpdateRowsEvent):
                event["action"] = "update"
                event.update(row["after_values"].items())
            elif isinstance(binlogevent, WriteRowsEvent):
                event["action"] = "insert"
                event.update(row["values"].items())

            print(event)
            sys.stdout.flush()

    stream.close()

   

>

**Comment by basebase** [comment]
=== WriteRowsEvent ===
Date: 2017-04-27T16:16:35
Log position: 2005
Event size: 19
Read bytes: 12
Table: test.join_test
Affected columns: 2
Changed rows: 1
Values:
--
* id : 444
* code : 2

**Comment by vinod-iref** [comment]
I too am facing this issue. Instead of reading the log_file from log_pos onwards it is reading from start of the log_file to log_pos.

**Comment by baloo** [comment]
You should be reading:
  - RotateEvent (header of the file), this describes the file you're reading, name, etc
  - HeartbeatLogEvent (introduced in 0.11): this is intended to be played by mysql-master if no traffic happens on a socket, but this is also used to replace "filtered" event (the one before the position you specified, or just before the gtid you specified). But that only works if you specify slave_heartbeat in your client connection.

If this is not the case, could you please provide me with logs or a reproducible environment?

**Comment by vinod-iref** [comment]
Hi,
This is my code:

    from pymysqlreplication.row_event import (
        DeleteRowsEvent,
        UpdateRowsEvent,
        WriteRowsEvent,
    )
    from pymysqlreplication import BinLogStreamReader

    mysql = {
        'host' : '127.0.0.1',
        'port' : 3306,
        'user' : 'user',
        'passwd' : 'pass',
        'db' : 'test'
    }

    def main():
        stream = BinLogStreamReader(
                connection_settings=mysql,
                only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent],
                only_schemas=["test"],
                log_file='mysql-bin.000003',
                log_pos=58865050,
                server_id=100)

        for binlogevent in stream:
            print stream.log_file, stream.log_pos, type(binlogevent)

    if __name__ == '__main__':
        main()

And this is my output:

    mysql-bin.000003 686 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 2064 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 3414 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 4764 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 4971 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 5187 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 6565 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 7915 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 8383 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 9761 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 11111 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 12489 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 13839 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 14046 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 14262 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 15612 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 16080 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 16483 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 16910 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 17305 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 17700 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 18135 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 19513 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 20863 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 22213 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 23591 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 24941 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 25148 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 25364 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 25832 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 26209 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    .
    .
    .
    mysql-bin.000003 74015153 <class 'pymysqlreplication.row_event.WriteRowsEvent'>
    mysql-bin.000003 74016531 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74017881 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74019231 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74019438 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74019654 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74021032 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74022382 <class 'pymysqlreplication.row_event.UpdateRowsEvent'>
    mysql-bin.000003 74023125 <class 'pymysqlreplication.row_event.WriteRowsEvent'>

I used the library once before and it worked fine. I am not sure what I am doing wrong this time.

**Comment by wentaotoyou** [comment]
You can find this in the source code: 
> log_pos: Set replication start log pos (resume_stream should be true)

**Comment by paneq** [comment]
I expected the same problem, it turned out that `resume_stream` and `log_pos` and `log_file` (which I was missing) are mandatory.
