### ISSUE TITLE
Only_table option is not working properly

### ISSUE THREAD

**Issue by HarshitVarshney** [noplay/python-mysql-replication#209]
I am giving 
stream = BinLogStreamReader(connection_settings=MYSQL_SETTINGS,
                                server_id=3 ,
                                blocking=True,**only_tables=['test4']** ) 
But still its printing Events from other tables as well.

**Comment by abrarsheikh** [comment]
@HarshitVarshney are you sure you are receiving **DataEvent** from other tables? can you paste the output here.

**Comment by HarshitVarshney** [comment]
@abrarsheikh you can check my output here, Tell me if i doing something wrong

Next binlog file: mysql-bin.000009
()
=== FormatDescriptionEvent ===
Date: 2017-05-25T11:25:38
Log position: 120
Event size: 93
Read bytes: 0
()
=== QueryEvent ===
Date: 2017-05-25T13:49:18
Log position: 199
Event size: 56
Read bytes: 56
Schema: test
Execution time: 0
Query: BEGIN
()
=== QueryEvent ===
Date: 2017-05-25T13:49:18
Log position: 305
Event size: 83
Read bytes: 83
Schema: test
Execution time: 0
**Query: insert into test3 values (7,'7')**
()
=== XidEvent ===
Date: 2017-05-25T13:49:18
Log position: 336
Event size: 8
Read bytes: 8
Transaction ID: 43
()


As i dont want to record any activity which is not related to the tables i have provided in the only_tables array

**Comment by baloo** [comment]
`only_tables` only works with row events. Your are running `binlog_format` `MIXED` or `STATEMENT`, this option only works with `ROW` format. Therefor, you see data from other tables (because we do not parse statement to extract information out of sql format).

**Comment by baloo** [comment]
See `binlog_format` documentation: https://dev.mysql.com/doc/refman/5.7/en/binary-log-setting.html
