### ISSUE TITLE
In pymysql, what happens when the amount of data read is greater than the amount of data in the cache?

### ISSUE THREAD

**Issue by hardcao** [noplay/python-mysql-replication#215]

**Comment by hardcao** [comment]
def _read_bytes(self, num_bytes):
        self._sock.settimeout(self._read_timeout)
        bufsize = self._sock.getsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR);
        print ("buf == %s"%(bufsize))
        while True:
            try:

                data = self._rfile.read(num_bytes)
                break
            except (IOError, OSError) as e:
                if e.errno == errno.EINTR:
                    continue
                self._force_close()
                raise err.OperationalError(
                    CR.CR_SERVER_LOST,
                    "Lost connection to MySQL server during query (%s)" % (e,))
        if len(data) < num_bytes:
            self._force_close()
            raise err.OperationalError(
                CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
        return data



My binlog program:
            bin_log_data = []
            global_gtid = ""
            print "restart load log position"

  
            server_uuid = getServerUUID();
            gtid_str = server_uuid+":1-1"


            stream = BinLogStreamReader(connection_settings=MYSQL_SETTINGS,
                                            server_id=3,
                                            blocking=True,
                                        )

            for binlogevent in stream:
                 time.sleep(1)
                 binlogevent.dump();


alway my program closed

**Comment by baloo** [comment]
Please provide a pull request with a failing test case.
