### ISSUE TITLE
Get GTID error in python3

### ISSUE THREAD

**Issue by thinkdb** [noplay/python-mysql-replication#224]
I made some changes：

    def gtid(self):
        """GTID = source_id:transaction_id
        Eg: 3E11FA47-71CA-11E1-9E33-C80AA9429562:23
        See: http://dev.mysql.com/doc/refman/5.6/en/replication-gtids-concepts.html"""
        try:  
            # python2
            gtid = "%s%s%s%s-%s%s-%s%s-%s%s-%s%s%s%s%s%s" %\
                   tuple("{0:02x}".format(ord(c)) for c in self.sid)
        except: 
            # python 3
            gtid = "%s%s%s%s-%s%s-%s%s-%s%s-%s%s%s%s%s%s" % \
                   tuple("{0:02x}".format(c) for c in self.sid)
        gtid += ":%d" % self.gno
        return gtid

**Comment by Roguelazer** [comment]
+1 would like to see this fixed
