### ISSUE TITLE
Result length not requested length

### ISSUE THREAD

**Issue by nghiaminhle** [noplay/python-mysql-replication#226]
Dear all,

Today, i've got a exception:
Result length not requested length:
Expected=8643.  Actual=6.  Position: 595.  Data Length: 601

> The exception tracing: 
> Result length not requested length:
> Expected=8643.  Actual=6.  Position: 595.  Data Length: 601
> Traceback (most recent call last):
>  
>    for row in binlogevent.rows:
>   File "/python3.6/site-packages/pymysqlreplication/row_event.py", line 428, in rows
>     self._fetch_rows()
>   File "/python3.6/site-packages/pymysqlreplication/row_event.py", line 423, in _fetch_rows
>     self.__rows.append(self._fetch_one_row())
>   File "/python3.6/site-packages/pymysqlreplication/row_event.py", line 512, in _fetch_one_row
>     row["before_values"] = self._read_column_data(self.columns_present_bitmap)
>   File "/python3.6/site-packages/pymysqlreplication/row_event.py", line 130, in _read_column_data
>     values[name] = self.__read_string(2, column)
>   File "/python3.6/site-packages/pymysqlreplication/row_event.py", line 218, in __read_string
>     string = self.packet.read_length_coded_pascal_string(size)
>   File "/python3.6/site-packages/pymysqlreplication/packet.py", line 253, in read_length_coded_pascal_string
>     return self.read(length)
>   File "/python3.6/site-packages/pymysqlreplication/packet.py", line 153, in read
>     return self.packet.read(size)
>   File "/python3.6/site-packages/pymysql/connections.py", line 250, in read
>     raise AssertionError(error)
> AssertionError: Result length not requested length:
> Expected=8643.  Actual=6.  Position: 595.  Data Length: 601

When i remove the update rows event, the problem is gone away. 
My configuration:
```
stream = BinLogStreamReader(
                connection_settings=mysql_settings,
                server_id=121
                ,only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent]
                ,freeze_schema = False
                ,log_file='bin.002877'
                ,log_pos=753583192
                ,resume_stream = True
                ,auto_position = False
            )
```
I don't know the reason. Please help to figure out the solution for this solution

**Comment by baloo** [comment]
can you share the pymysql verion and the version of pymysqlreplication?

**Comment by tferreira** [comment]
I just got the same issue with WriteRowsEvent.
```
mysql-replication==0.15
PyMySQL==0.8.0
```

I tried with older versions of PyMySQL but had the same errors.

**Comment by lumenghe** [comment]
I got the same error with
```
mysql-replication==0.19
PyMySql==0.9.2
```

**Comment by juravlikk** [comment]
Got the same with
```
mysql-replication==0.19
PyMySql==0.8.2
```
After some investigation found that it doesn't depend on the library version and caused by wrong value retrieving for `JSONB_TYPE_LITERAL` type (`true`, `false`, `null`). It occurs only for large JSON documents and works well for small.
https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/packet.py#L389

I've raised PR to fix this - https://github.com/noplay/python-mysql-replication/pull/307

**Comment by MintooJinnu** [comment]
The above issue is not specifically raised for JSON Literal method correct? It is still happening in reading varchar data(read_length_coded_pascal_string) @baloo
