### ISSUE TITLE
Can we configure this library to stream out of a MySQL slave?

### ISSUE THREAD

**Issue by ravindranathakila** [noplay/python-mysql-replication#229]

**Comment by noplay** [comment]
Yes it should work

**Comment by ravindranathakila** [comment]
I think the library uses SHOW MASTER STATUS. Will this command be effective on the slave?

**Comment by baloo** [comment]
Yes. You can chain any number of slave, it just slows down the replication.

That's the setup we use python-mysql-replication. master -> slave -> python-mysql-replication
