### ISSUE TITLE
How to solve this error I got received in the first run?

### ISSUE THREAD

**Issue by rajasimon** [noplay/python-mysql-replication#234]
I just installed and try to run this replication a try but in the first run I've got these error...

    TypeError: __init__() takes at least 3 arguments (3 given)

I have thease code in `mysql_sync.py`

```
class MySQLSync(object):
    def __init__(self):
        self.stream = BinLogStreamReader(
            connection_settings=MYSQL_SETTINGS,
            only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent])

    def stream_event(self):
        for event in self.stream:
            prefix = "{}:{}:".format(event.schema, event.table)

            for row in event.rows:
                if isinstance(event, WriteRowsEvent):
                    logger.info('Event {}'.format(prefix))

        self.stream.close()
```

Traceback
```
Traceback (most recent call last):
  File "mysql_sync.py", line 37, in <module>
    only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent])
TypeError: __init__() takes at least 3 arguments (3 given)
```

**Comment by rajasimon** [comment]
This error stops when I include `server_id` in `stream` statement

        stream = BinLogStreamReader(
            connection_settings=MYSQL_SETTINGS,
            server_id=1,
            only_events=[DeleteRowsEvent, WriteRowsEvent, UpdateRowsEvent])

Although now I have into another issue this time when I run mysql_sync.py it's not working no error message or blank screen.

```
(data-sync-module-I0lVjvq9) simon@ENGINE:~/Workspace/data-sync-module$ python mysql_sync.py 
(data-sync-module-I0lVjvq9) simon@ENGINE:~/Workspace/data-sync-module$ python mysql_sync.py 
```

**Comment by baloo** [comment]
@rajasimon may I close this issue then?

**Comment by rajasimon** [comment]
I close it now. Turns out after editing the mysql conf file withe replication configuration it's working. Also can  you please shed the light how do I run this in event loop will be very helpful thank you.
