### ISSUE TITLE
import 1w records into mysql,The replication will delay more than 1 minutes!

### ISSUE THREAD

**Issue by queryDuan** [noplay/python-mysql-replication#237]
import 1w records into mysql,The replication will delay more than 1 minutes!why?How to resolve it?

**Comment by baloo** [comment]
Please provide code samples

**Comment by queryDuan** [comment]
I has position the problem,The TableMapEvent which is the reason caused.
`        if self.table_id in table_map:
            self.column_schemas = table_map[self.table_id].column_schemas
        else:
            self.column_schemas = self._ctl_connection._get_table_information(self.schema, self.table)`
the table_map is from class 'BinLogStreamReader' and usually is {}。so every time ,it will get table info by   _ctl_connection from master. Not by parse binlog.
