### ISSUE TITLE
Realtime streaming?

### ISSUE THREAD

**Issue by Amet13** [noplay/python-mysql-replication#240]
Hello.
How can I stream in realtime?
I'm trying to run [example](https://github.com/noplay/python-mysql-replication/blob/master/examples/logstash/mysql_to_logstash.py) it can show insert data from binlog but don't listen as a daemon.
```
# python test1.py
{"name": "qwe", "email": "xuz@abc.com", "action": "insert", "table": "authors", "id": 1, "schema": "prod"}
{"name": "rty", "email": "xuz@abc.com", "action": "insert", "table": "authors", "id": 1, "schema": "prod"}
```
Will I need to write custom python wrapper for it?

**Comment by gonzalodiaz** [comment]
+1 Same use case here.

**Comment by baloo** [comment]
Here is an (untested) example of how we use binlog streamer at work:
```python
class StreamReader(object):
    def __init__(self, config):
        self.actions = []
        self.stream = BinLogStreamReader(
            connection_settings=config['mysql'],
            blocking=True)

    def start_replication(self):
        rowevents = WriteRowsEvent, UpdateRowsEvent, DeleteRowsEvent

        for event in self.loop():
            # event.dump()  # in case of debug, break the glass

            if isinstance(event, GtidEvent):
                self.begin(event)
            elif isinstance(event, XidEvent):
                self.commit(event)
            elif isinstance(event, rowevents):
                self.actions.extend(list(event))

    def loop(self):
        istream = iter(self.stream)
        while True:
            yield next(istream)

    def begin(self, event):
        if self.gtid is not None:
            if self.actions:
                raise RuntimeError('Got gtid %r, but still processing gtid %r'
                                   % (event.gtid, self.gtid))
            else:
                # A new gtid event without a transaction/row events
                # Most probably the last gtid we got was a schema change
                # we choose to ignore
                # Only try to append if not already in set (this will be the
                # case when starting replication from an alter)
                if self.filter_gtid and self.gtid.sid not in self.filter_gtid:
                    pass
                elif self.gtid not in self.bdb.get_gtid():
                    self.bdb.set_gtid(self.bdb.get_gtid() + self.gtid)

        self.gtid = Gtid(event.gtid)

    def commit(self, event):
        # Do something here with events

        self.actions = []
```

**Comment by Amet13** [comment]
Thanks.

**Comment by joeportela** [comment]
@baloo How do you deal with lost MySQL connections (db restarts, etc.)?
I have a similar implementation, but if the connection is lost, it just sits there waiting forever.

**Comment by joeportela** [comment]
I think i figured it out - I passed in a read_timeout to the mysql connection parameters.  Now I'm raising an error if the stream iteration ends.

**Comment by diegobill** [comment]
Hi @joeportela ,
could you share your code passing the read_timeout and and raising the error?
thanks

**Comment by joeportela** [comment]
I don't have any code to share, but I can explain how it behaves.  Start by
adding read_timeout to your mysql connection_settings when creating your
BinLogStreamReader, i.e. stream =
BinLogStreamReader(connection_settings={'host': x, 'port': y,
'read_timeout': 600}, ...).  Then, when you are iterating over events in
the stream, (for binlogevent in stream:...), if the read_timeout occurs,
the iterator simply raises the StopIteration and your code proceeds past
the loop.  Personally, I deal with it by manually raising a
OperationalError when I get past the for loop.
