### ISSUE TITLE
add a project to readme's  "Projects using this library" section

### ISSUE THREAD

**Issue by leafonsword** [noplay/python-mysql-replication#241]
[binlog2sql](https://github.com/danfengcao/binlog2sql) is a popular binlog parser that could convert raw binlog to sql and could generate flashback sql from raw binlog; Hope this project listed in  readme's  "Projects using this library" section~

**Comment by baloo** [comment]
Sure!
Just open a pull request for it :)

**Comment by noplay** [comment]
Yes a pull request is welcome. Nice project !

Le lun. 8 janv. 2018 à 19:29, Arthur Gautier <notifications@github.com> a
écrit :
