### ISSUE TITLE
support GTID for mariadb

### ISSUE THREAD

**Issue by the4thdoctor** [noplay/python-mysql-replication#274]
Not sure how much is difficult or if possible so please feel free to reject.
However would be nice to have the GTID event from mariadb as well.

Thanks

**Comment by baloo** [comment]
mariadb has a different gtid format than all other mysql forks. From my understanding (I did the gtid implementation here), it is very painful to support both. If you have an idea how to support both, and want to provide an implementation, I'd be happy to discuss it with you and hopefully merge it, in the meantime, I'll close this issue.

**Comment by the4thdoctor** [comment]
I can have a look how mariadb works. thank you for now.

**Comment by Samira-El** [comment]
Hi @the4thdoctor, have you looked into this?

**Comment by Samira-El** [comment]
@baloo, could you share some insights on why it is very painful to support both

**Comment by the4thdoctor** [comment]
@Samira-El I'm planning to check asap. I'm aware that the mariadb gtid is completely different from mysql. for the latter I had to do a lot of fiddling to ensure pgchameleon could send the correct gtid when auto positioning
