### ISSUE TITLE
can't get table_map when replication user no select privileges

### ISSUE THREAD

**Issue by G8bao7** [noplay/python-mysql-replication#291]
when replication user no select privileges, binlogevent.rows is empty.
because can't select table columns information
if can print reason when  can't get table_map , it will be good

**Comment by LeeByungwoo** [comment]
I solved your problem thanks to you

**Comment by jamesamurr-bind** [comment]
I had this experience too. It took me longer than I'd like to admit to find the solution. Against Aurora-MySQL 5.6 you need the following permissions for the user.

REPLICATION CLIENT
REPLCIATION SLAVE
SELECT

**Comment by aleimu** [comment]
grant replication slave, reload, super on *.* to 'XXXX'@'%' identified by 'XXXX';
GRANT ALL PRIVILEGES ON `XXXX`.* TO 'XXXX'@'%' WITH GRANT OPTION;
flush privileges;

Your problem may be solved.
