### ISSUE TITLE
How to simulate MySQL natural replication with GTID mode？

### ISSUE THREAD

**Issue by BlackWatchuser** [noplay/python-mysql-replication#294]
here is the question:
    Recently, i want to get the binlog offset( position  number ) from a given binlog file by giving a known GTID number. When the binlog file size is very big, it will be very slow.  so how to make it quickly.

**Comment by baloo** [comment]
There is nothing much you can do. This is inherent to the way gtid works in mysql.

Mysql server has to scan the binlog it has on disk to get the gtid position. If the binlog is large, this may be slow.
One trick is to lower the binlog file size, and increase the number of binlog files, you get the same amount of data, but more segmented and scanning through one binlog file is quicker. But whatever happens, mysql has to scan through all a binlog file to fetch the gtid position you're interested in.

**Comment by BlackWatchuser** [comment]
ok，appreciate your reply.
