### ISSUE TITLE
The length of extra_data is calculated inconsistent with the document

### ISSUE THREAD

**Issue by lifani** [noplay/python-mysql-replication#297]
In the document "https://dev.mysql.com/doc/internals/en/rows-event.html#packet-Binlog::RowsEventExtraData" the length of extra_data is calculated as [extra_data_len - 2], but in the rows_event.py is calculated as [extra_data_len / 8]。Why？

**Comment by baloo** [comment]
no idea, but feel free to throw a PR to fix that :)

**Comment by dongwook-chan** [comment]
@lifani 
This issue was fixed in https://github.com/noplay/python-mysql-replication/pull/355 and released in version 0.26.
