### ISSUE TITLE
Incorrect column order with limited permissions to MySQL user

### ISSUE THREAD

**Issue by shubhbhargav** [noplay/python-mysql-replication#299]
**Description**
MySQL supports limited column access, such as `GRANT SELECT (col1, col2) ON <some-db>.<some-table> TO <some-user>`. This helps in avoiding undesired access to the user.

When given limited access to the user (doing the streaming), incoming data comes with `__dropped_col_<some-number>__`. This is expected for the columns which user doesn't have access to but the order in which the columns are dropped is wrong.

**Steps to reproduce:**
- Setup MySQL database and table as the following
```sql
CREATE DATABASE test;

CREATE TABLE blah_multi_columns (
	col_a int(11),
	col_b int(11),
	col_c int(11),
	col_d int(11),
	col_e int(11)
);

CREATE USER 'streamer'@'%' identified by 'not-so-secure';

GRANT SELECT (col_a, col_c, col_e) ON test.blah_multi_columns TO 'streamer'@'%';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'streamer'@'%';

INSERT INTO blah_multi_columns VALUES (1, 2, 3, 4, 5);
```
- Start the streamer and the following row event will come:
```json
{
	"schema": "test",
	"table": "blah_multi_columns",
	"type": "WriteRowsEvent",
	"row": {
		"col_a": 1,
		"col_c": 2,
		"col_e": 3,
		"__dropped_col_3__": 4,
		"__dropped_col_4__": 5
	}
}
```

Here the expected row should have been:
```json
{
	"schema": "test",
	"table": "blah_multi_columns",
	"type": "WriteRowsEvent",
	"row": {
		"col_a": 1,
		"col_c": 3,
		"col_e": 5,
		"__dropped_col_2__": 2,
		"__dropped_col_4__": 4
	}
}
```

**Tentative solution:**
We've fixed the issue temporarily using `ORDINAL POSITION` column in `information_schema`.`columns` table (to get schema definition for the table). This helps in dropping the intended columns. It will be really helpful if the same fix can be added to pymysqlreplication (or an alternate would work as well).

**Comment by baloo** [comment]
pr welcome :)
