### ISSUE TITLE
Resuming from log_pos results in events being thrown away

### ISSUE THREAD

**Issue by lijok** [noplay/python-mysql-replication#314]
In row based replication, when you set log_pos and resume_stream, all events are thrown out until it reaches the next TableMap event, at which point it resumes as normal.

Any chance of adding the functionality to find the last TableMap event when resuming from log_pos, then resuming reading events from log_pos as normal?

**Comment by baloo** [comment]
you need to set log_file otherwise it has no effect.

**Comment by eimantas-gecas-axomic** [comment]
log_file is set

**Comment by eimantas-gecas-axomic** [comment]
> you need to set log_file otherwise it has no effect.

log_file is set

**Comment by lijok** [comment]
> you need to set log_file otherwise it has no effect.

log_file is set
would it help if I posted an example of the issue?
