### ISSUE TITLE
Update PyMySql version requirement

### ISSUE THREAD

**Issue by benjaminsky** [noplay/python-mysql-replication#353]
https://github.com/noplay/python-mysql-replication/blob/main/setup.py#L53

Minimum version is set to `0.6` but below version `0.10.0` charset encoding from `latin1` is handled incorrectly.

https://github.com/PyMySQL/PyMySQL/commit/a4f98474dc00347c15a43012884f8305ac7fa54f

Updating to `0.10.0` fixed our issue.

**Comment by noplay** [comment]
Thanks I will change that in 0.26 coming out today.
