### ISSUE TITLE
sql_mode for tests

### ISSUE THREAD

**Issue by dongwook-chan** [noplay/python-mysql-replication#356]
Most of the tests seems to be written for 5.6 or lower version of MySQL.

And came 5.7, and contributors wanted existing tests to pass.
However, default sql_mode were changed.
| version | sql_mode |
| ------- | ---------- |
| 5.6       | **NO_ENGINE_SUBSTITUTION** |
| 5.7       | ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, **NO_ENGINE_SUBSTITUTION** |

They added set_sql_mode() at the beginning of each test.
This method sets the session sql_mode to 5.6 default, 'NO_ENGINE_SUBSTITUTION'.
This allowed tests to be passed for MySQL 5.7.

Now we have 8.0 and it's high time we determine whether we should keep 5.6 default sql_mode for testing its descendants.
I think each version should be tested as its default value.

**Comment by noplay** [comment]
I agree with you. We should did this .

**Comment by dongwook-chan** [comment]
I appreciate your comment.
I'll have all versions tested against its default sql_mode.
